// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	ID        int64            `json:"id"`
	Title     string           `json:"title"`
	Content   string           `json:"content"`
	AuthorID  pgtype.Int8      `json:"author_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type ArticleView struct {
	ID        int64            `json:"id"`
	UserID    int64            `json:"user_id"`
	ArticleID int64            `json:"article_id"`
	ViewedAt  pgtype.Timestamp `json:"viewed_at"`
}

type User struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
}
