// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	ID        int64
	Title     string
	Content   string
	AuthorID  pgtype.Int8
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type User struct {
	ID       int64
	Name     string
	Email    string
	Username string
	Password string
}
